### ISSUE TITLE
check_indexes: run without blocking during a vacuum_full or cluster

### ISSUE THREAD

**Issue by SmartPostgres** [SmartPostgres/Box-of-Tricks#32]
Right now, if you do a vacuum_full or a cluster, and then you query check_indexes, check_indexes is blocked.

**Comment by SmartPostgres** [comment]
Complete.

**Comment by binumarar** [comment]
Could you please add how much Index fragmented/bloated as well

**Comment by SmartPostgres** [comment]
@binumarar that's a separate feature request, unrelated to this issue. Please don't add unrelated comments to Github issues. Thanks for understanding.

**Comment by binumarar** [comment]
Thank you for the update.
